# NFS libraries + config on UniFi NAS (infra01). Paths created on the share before first sync.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-audiobooks-nfs
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
    - nolock
  nfs:
    server: 192.168.0.25
    path: /var/nfs/shared/infra01/audiobookshelf/audiobooks
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-audiobooks
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: audiobookshelf-audiobooks-nfs
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-podcasts-nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
    - nolock
  nfs:
    server: 192.168.0.25
    path: /var/nfs/shared/infra01/audiobookshelf/podcasts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-podcasts
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: audiobookshelf-podcasts-nfs
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-metadata-nfs
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
    - nolock
  nfs:
    server: 192.168.0.25
    path: /var/nfs/shared/infra01/audiobookshelf/metadata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: audiobookshelf-metadata-nfs
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-config-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
    - nolock
  nfs:
    server: 192.168.0.25
    path: /var/nfs/shared/infra01/audiobookshelf/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: audiobookshelf-config-nfs
  resources:
    requests:
      storage: 5Gi
