apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loki-stadthagen-dev
spec:
  secretName: loki-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - loki.stadthagen.dev
