apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newt
helmCharts:
  - name: newt
    repo: https://charts.fossorial.io
    version: 1.5.0
    releaseName: newt
    namespace: newt
    valuesFile: values.yaml
