apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headlamp-stadthagen-dev
spec:
  secretName: headlamp-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - headlamp.stadthagen.dev
