apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  annotations:
    longhorn.io/volume-replica-count: "1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 5Gi
