apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: idp-stadthagen-dev
  namespace: authentik
spec:
  secretName: idp-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - idp.stadthagen.dev
