apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastruktur
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: Infrastruktur — Homelab platform
  sourceRepos:
    - https://github.com/HenryHST/minilab
  destinations:
    - server: https://kubernetes.default.svc
      namespace: certmanager
    - server: https://kubernetes.default.svc
      namespace: longhorn-system
    - server: https://kubernetes.default.svc
      namespace: newt
    - server: https://kubernetes.default.svc
      namespace: grafana
    - server: https://kubernetes.default.svc
      namespace: loki
    - server: https://kubernetes.default.svc
      namespace: alertmanager
    - server: https://kubernetes.default.svc
      namespace: authentik
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
