apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastruktur
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: Infrastruktur — Homelab platform
  sourceRepos:
    - https://github.com/HenryHST/minilab
    - https://prometheus-community.github.io/helm-charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: certmanager
    # cert-manager chart: leader-election Roles/RoleBindings + webhook auth reader
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: longhorn-system
    - server: https://kubernetes.default.svc
      namespace: system-upgrade
    - server: https://kubernetes.default.svc
      namespace: newt
    - server: https://kubernetes.default.svc
      namespace: pangolin-publish
    - server: https://kubernetes.default.svc
      namespace: registry
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: authentik
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
