apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bytestash
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/HenryHST/minilab
    path: apps/bytestash
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: bytestash
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
