apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - appproject-infrastruktur.yaml
  - cert-manager.yaml
  - longhorn.yaml
  - newt.yaml
  - system-upgrade-controller.yaml
  - metrics-server.yaml
  - grafana.yaml
  - prometheus.yaml
  - unifipoller.yaml
  - authentik.yaml
  - termix.yaml
  - headlamp.yaml
  - omni-tools.yaml
  - it-tools.yaml
  - pgweb.yaml
  - web.yaml
  - drawio.yaml
  - status.yaml
  - grafana-loki.yaml
  - alertmanager.yaml
  - vaultwarden.yaml
