apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - infrastruktur-project.yaml
  - bootstrap/
  - infra-applicationset.yaml
  - longhorn.yaml
  - system-upgrade-controller.yaml
  - unifipoller.yaml
  - authentik.yaml
  - termix.yaml
  - headlamp.yaml
  - omni-tools.yaml
  - it-tools.yaml
  - pgweb.yaml
  - web.yaml
  - drawio.yaml
  - status.yaml
  - vaultwarden.yaml
  - pangolin-publish.yaml
  - stirling-pdf.yaml
