apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: termix-stadthagen-dev
  namespace: termix
spec:
  secretName: termix-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - termix.stadthagen.dev
