apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: omni-tools-stadthagen-dev
spec:
  secretName: omni-tools-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - omni-tools.stadthagen.dev
