apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: status-stadthagen-dev
  namespace: uptimekuma
spec:
  secretName: status-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - status.stadthagen.dev
