apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: termix
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`termix.stadthagen.dev`)
      kind: Rule
      services:
        - name: termix
          port: 8080
  tls:
    secretName: termix-tls
