apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: termix
helmCharts:
  - name: termix
    releaseName: termix
    namespace: termix
    includeCRDs: false
    valuesFile: values.yaml
resources:
  - certificate.yaml
  - postgres.yaml
