apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-settings
  namespace: searxng
data:
  settings.yml: |
    use_default_settings: true
    general:
      instance_name: "SearXNG Homelab"
      enable_metrics: false
    server:
      base_url: https://searxng.stadthagen.dev/
      limiter: false
      image_proxy: true
    search:
      safe_search: 0
      autocomplete: ""
      default_lang: "de"
      formats:
        - html
