---
- Repositories:
  - Devops-labs:
    - icon: si-github-#FFFFFF
      href: https://github.com/henryhst/devops-labs
  - Dotfiles:
    - icon: si-github-#FFFFFF
      href: https://github.com/henryhst/dotfiles
  - Cheat-Sheets:
    - icon: si-github-#FFFFFF
      href: https://github.com/henryhst/cheat-sheets
  - minilab:
    - icon: si-github-#FFFFFF
      href: https://github.com/HenryHST/minilab

- Developer:
    - Github:
        - abbr: GH
          icon: si-github-#FFFFFF
          href: https://github.com/
