apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgweb-stadthagen-dev
spec:
  secretName: pgweb-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - pgweb.stadthagen.dev
