apiVersion: apps/v1
kind: Deployment
metadata:
  name: status
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: status
  template:
    metadata:
      labels:
        app: status
    spec:
      containers:
        - name: status
          image: louislam/uptime-kuma:2.0.0-beta.4
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: data
              mountPath: /app/data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
      volumes:
        - name: data
          hostPath:
            path: /var/lib/uptimekuma
            type: DirectoryOrCreate
