# Longhorn 1-replica (cluster disks too small for default 3-replica SC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptimekuma-data
  namespace: uptimekuma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-loki-local
  resources:
    requests:
      storage: 4Gi
