# Longhorn 1-replica local (disks tight; 1Gi is enough for Uptime Kuma SQLite)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptimekuma-data
  namespace: uptimekuma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-loki-local
  resources:
    requests:
      storage: 1Gi
