apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drawio-stadthagen-dev
  namespace: drawio
spec:
  secretName: drawio-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - drawio.stadthagen.dev
