apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus.prometheus.svc.cluster.local:9090
        isDefault: true
        editable: false
        jsonData:
          httpMethod: POST
          timeInterval: 30s

      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://loki-gateway.loki.svc.cluster.local
        isDefault: false
        editable: false
        jsonData:
          maxLines: 1000
          tlsSkipVerify: false

      - name: Alertmanager
        type: alertmanager
        uid: alertmanager
        access: proxy
        url: http://alertmanager.alertmanager.svc.cluster.local:9093
        editable: false
        jsonData:
          implementation: prometheus
          handleGrafanaManagedAlerts: false

      - name: Hetzner Cloud
        type: apricote-hcloud-datasource
        uid: hetzner-cloud
        access: proxy
        editable: false
        jsonData: {}
        secureJsonData:
          apiToken: ${HCLOUD_API_TOKEN}
