apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: prometheus-data
  resources:
    requests:
      storage: 10Gi
