apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: unpoller
helmCharts:
  - name: unpoller
    repo: https://unpoller.github.io/helm-chart
    version: 2.4.0
    releaseName: unpoller
    namespace: unpoller
    valuesFile: values.yaml
